### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by prestonvanloon** [Zxilly/go-size-analyzer#240]
**Describe the bug**

```
panic: interface conversion: interface {} is nil, not string

goroutine 66 [running]:
github.com/Zxilly/go-size-analyzer/internal/knowninfo.(*KnownInfo).AddDwarfVariable(0xc000285030, 0xc00fbdc3c0, 0xc0005ec000, 0xc010515200, 0x8)
        /home/preston/go/pkg/mod/github.com/!zxilly/go-size-analyzer@v1.7.3/internal/knowninfo/dwarf.go:57 +0xa05
github.com/Zxilly/go-size-analyzer/internal/knowninfo.(*KnownInfo).GetDwarfCompileUnitFeeder.func1(0xc010d3fc80?)
        /home/preston/go/pkg/mod/github.com/!zxilly/go-size-analyzer@v1.7.3/internal/knowninfo/dwarf.go:209 +0x3b
github.com/Zxilly/go-size-analyzer/internal/knowninfo.(*KnownInfo).TryLoadDwarf.func1()
        /home/preston/go/pkg/mod/github.com/!zxilly/go-size-analyzer@v1.7.3/internal/knowninfo/dwarf.go:246 +0x9b
created by github.com/Zxilly/go-size-analyzer/internal/knowninfo.(*KnownInfo).TryLoadDwarf in goroutine 1
        /home/preston/go/pkg/mod/github.com/!zxilly/go-size-analyzer@v1.7.3/internal/knowninfo/dwarf.go:242 +0x179
```

**To Reproduce**

This is running gsa on github.com/prysmaticlabs/prysm.

```bash
# Build binary with debug symbols
bazel build //cmd/beacon-chain -c dbg

# Run gsa
gsa --tui bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain

# Observe panic
```

**Expected behavior**

It works.

**Comment by Zxilly** [comment]
Can you upload the binary that is experiencing the problem? I don't have bazel installed locally.

**Comment by Zxilly** [comment]
Please try [1.7.4](https://github.com/Zxilly/go-size-analyzer/releases/tag/v1.7.4), which should resolve this problem.

**Comment by prestonvanloon** [comment]
Thanks, 1.7.4 works!
